<a href="https://colab.research.google.com/github/gopalsah9841-eng/Math/blob/main/Workshop6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*   **Name:Gopal sah**
*   *University ID: 2596218*

In [ ]:
# -*- coding: utf-8 -*-
"""
This is a script file for Week 5 Workshop.

Author: Rahul Mourya
"""

import numpy as np

if __name__ == "__main__":

    """ Problem 1: Create a 2D ndarray (Matrix) of type Float,
    e.g., [[1,2,3],[4,5,6],[7,8,9]]
    and see its properties/attributes """

    arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
    print("Array =")
    print(arr)
    print("Data Type of the Array                     =", arr.dtype)
    print("Number of dimensions of the Array          =", arr.ndim)
    print("Shape of the Array                         =", arr.shape)
    print("Size of the Array                          =", arr.size)
    print("Number of bytes used by each element of the Array =", arr.itemsize)
    print("Total bytes used by the Array              =", arr.nbytes)
    print("Memory Layout information                  =", arr.flags)

Array =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Data Type of the Array                     = float64
Number of dimensions of the Array          = 2
Shape of the Array                         = (3, 3)
Size of the Array                          = 9
Number of bytes used by each element of the Array = 8
Total bytes used by the Array              = 72
Memory Layout information                  =   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [ ]:
"""Problem 2: Create a 2D ndarray (Matrix) of shape (4,5) with all elements
equal to 3.0 and print the matrix. """
arr2 = 3 * np.ones((4,5), dtype=float)
print("Array = ")
print(arr2)
print("Shape = ", arr2.shape)
print("DataType = ", arr2.dtype)

Array = 
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape =  (4, 5)
DataType =  float64


In [ ]:
arr1 = np.full((4,5), 3)
print("Array = ")
print(arr1)

Array = 
[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [ ]:
"""Problem 4: Construct a matrix [a_i,j ] of shape (3,3) whose elements
are given by a_i,j = 1/2 |i - 3j|.
This is the same question in the lecture slide."""

# Note: in Python indexing starts at 0
arr4 = np.fromfunction(lambda i, j: np.abs(i + 1 - 3*(j + 1)) / 2, (3, 3), dtype=int)

print("Array = ")
print(arr4)
print("Shape = ", arr4.shape)
print("DataType = ", arr4.dtype)

Array = 
[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
Shape =  (3, 3)
DataType =  float64


In [ ]:
arr1 = [1,2,3,4]
print(np.diag(arr1))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
arr1 = np.array([[0,1,2,3,4], [1,2,3,4,5], [2,3,4,5,6], [3,4,5,6,7]])
print("Array =")
print(arr1)
print("New Array =")
print(arr1[0:3, 0:3])

Array =
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
New Array =
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
arr1 = np.array([[1,2,3,4], [4,5,6], [7,8,9]])
arr2 = np.array([[1,1,1], [2,2,2]])
arr3  = arr1 + arr2
print(arr3)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
def dot_product(vec1, vec2):
    # flatten the intput vectors
    vec1 = vec1.flatten()
    vec2 = vec2.flatten()
    return np.sum(np.multiply(vec1, vec2))

def matrix_vector_product(mat, vec):
    m,n = mat.shape
    p,q = vec.shape

    assert n == p, "the matrix and vector are not compatible for multiplication!"

    # create a ndarray to store the result
    result = np.zeros((m,q), dtype=float)

    # Loop to perform Matrix-Vector product
    # Perform dot product between the vector and each row of the matrix
    for i in range(m):
        result[i] = dot_product(mat[i,:], vec)

    return result

if __name__ == "__main__":
  """ Part 2: Problem 2: Given a matrix and a vector, write a function that
  performs Matrix-Vector product. """
  mat1 = np.full((3,3), 3, dtype=int)
  vec1 = np.full((3,1), 2, dtype=int)
  print("Matrix = ")
  print(mat1)
  print("Vector = ")
  print(vec1)

  # Call the function matrix_vector_product(mat, vec)
  result1 = matrix_vector_product(mat1, vec1)
  print("Result = ")
  print(result1)

  # Check with numpy in-built function for multiplication
  result2 = mat1 @ vec1
  print("Result = ")
  print(result2)

Matrix = 
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector = 
[[2]
 [2]
 [2]]
Result = 
[[18.]
 [18.]
 [18.]]
Result = 
[[18]
 [18]
 [18]]


In [ ]:
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr1 @ arr2)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
def check_symmetric(arr1):
  arr2 = arr1.transpose()
  return np.array_equal(arr1, arr2)
arr1 = np.array([[0, 1, 2],[1, 0, 3],[2, 3, 0]])
print(check_symmetric(arr1))

True
